# Generated by Django 5.2.8 on 2025-11-15 12:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MORNING', 'Өглөө'), ('EVENING', 'Орой'), ('CHILDREN', 'Хүүхэд')], max_length=20, unique=True, verbose_name='Ангийн төрөл')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
            ],
            options={
                'verbose_name': 'Ангийн төрөл',
                'verbose_name_plural': 'Ангийн төрлүүд',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('last_name', models.CharField(max_length=100, verbose_name='Овог')),
                ('phone', models.CharField(max_length=20, verbose_name='Утас')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='И-мэйл')),
                ('hire_date', models.DateField(verbose_name='Ажилд орсон огноо')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
            ],
            options={
                'verbose_name': 'Багш',
                'verbose_name_plural': 'Багш нар',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('last_name', models.CharField(max_length=100, verbose_name='Овог')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Утас')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='И-мэйл')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Төрсөн огноо')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Элссэн огноо')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
            ],
            options={
                'verbose_name': 'Сурагч',
                'verbose_name_plural': 'Сурагчид',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Огноо')),
                ('weekday', models.IntegerField(choices=[(1, 'Даваа'), (3, 'Лхагва'), (5, 'Баасан'), (6, 'Бямба'), (0, 'Ням')], verbose_name='Гараг')),
                ('start_time', models.TimeField(verbose_name='Эхлэх цаг')),
                ('end_time', models.TimeField(verbose_name='Дуусах цаг')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aikido_app.classtype', verbose_name='Ангийн төрөл')),
            ],
            options={
                'verbose_name': 'Хичээлийн хуваарь',
                'verbose_name_plural': 'Хичээлийн хуваарь',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Гүйлгээний огноо')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Дүн')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('payment_month', models.DateField(blank=True, null=True, verbose_name='Төлбөрийн сар')),
                ('bank_reference', models.CharField(blank=True, max_length=200, verbose_name='Банкны лавлагаа')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Баталгаажсан эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aikido_app.student', verbose_name='Сурагч')),
            ],
            options={
                'verbose_name': 'Төлбөр',
                'verbose_name_plural': 'Төлбөрүүд',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEAD', 'Ахлах багш'), ('ASSISTANT', 'Туслах багш')], max_length=20, verbose_name='Үүрэг')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aikido_app.instructor', verbose_name='Багш')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to='aikido_app.classsession', verbose_name='Хичээл')),
            ],
            options={
                'verbose_name': 'Багшийн томилолт',
                'verbose_name_plural': 'Багшийн томилолтууд',
                'unique_together': {('session', 'instructor')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='Ирсэн эсэх')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн цаг')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='aikido_app.classsession', verbose_name='Хичээл')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aikido_app.instructor', verbose_name='Бүртгэсэн багш')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aikido_app.student', verbose_name='Сурагч')),
            ],
            options={
                'verbose_name': 'Ирц',
                'verbose_name_plural': 'Ирц',
                'ordering': ['-session__date'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
