# Generated by Django 5.2.8 on 2025-11-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0002_instructor_user_student_class_types_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='dan_rank',
            field=models.IntegerField(blank=True, choices=[(1, '1 дан'), (2, '2 дан'), (3, '3 дан'), (4, '4 дан'), (5, '5 дан'), (6, '6 дан'), (7, '7 дан'), (8, '8 дан')], null=True, verbose_name='Дан зэрэг'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='kyu_rank',
            field=models.IntegerField(blank=True, choices=[(1, '1 кюү'), (2, '2 кюү'), (3, '3 кюү'), (4, '4 кюү'), (5, '5 кюү'), (6, '6 кюү'), (7, '7 кюү'), (8, '8 кюү')], null=True, verbose_name='Кюү зэрэг'),
        ),
        migrations.AddField(
            model_name='student',
            name='dan_rank',
            field=models.IntegerField(blank=True, choices=[(1, '1 дан'), (2, '2 дан'), (3, '3 дан'), (4, '4 дан'), (5, '5 дан'), (6, '6 дан'), (7, '7 дан'), (8, '8 дан')], null=True, verbose_name='Дан зэрэг'),
        ),
        migrations.AddField(
            model_name='student',
            name='kyu_rank',
            field=models.IntegerField(blank=True, choices=[(1, '1 кюү'), (2, '2 кюү'), (3, '3 кюү'), (4, '4 кюү'), (5, '5 кюү'), (6, '6 кюү'), (7, '7 кюү'), (8, '8 кюү')], null=True, verbose_name='Кюү зэрэг'),
        ),
    ]
