# Generated by Django 5.2.8 on 2025-11-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0003_instructor_dan_rank_instructor_kyu_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='current_rank_date',
            field=models.DateField(blank=True, null=True, verbose_name='Одоогийн зэрэг авсан огноо'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_rank_date',
            field=models.DateField(blank=True, null=True, verbose_name='Одоогийн зэрэг авсан огноо'),
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_type', models.CharField(choices=[('kyu', 'Кюү'), ('dan', 'Дан')], max_length=10, verbose_name='Зэрэг төрөл')),
                ('rank_number', models.IntegerField(verbose_name='Зэрэг дугаар')),
                ('obtained_date', models.DateField(verbose_name='Авсан огноо')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн огноо')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='aikido_app.instructor', verbose_name='Багш')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='aikido_app.student', verbose_name='Сурагч')),
            ],
            options={
                'verbose_name': 'Зэрэг цолын түүх',
                'verbose_name_plural': 'Зэрэг цолын түүхүүд',
                'ordering': ['-obtained_date'],
            },
        ),
    ]
