# Generated by Django 5.2.8 on 2025-11-15 13:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0004_instructor_current_rank_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_note',
            field=models.TextField(blank=True, verbose_name='Төлбөрийн тайлбар'),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сарын төлбөр'),
        ),
    ]
