# Generated by Django 5.2.8 on 2025-11-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0005_student_fee_note_student_monthly_fee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructorassignment',
            unique_together={('session', 'instructor', 'role')},
        ),
    ]
