# Generated by Django 5.2.8 on 2025-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0006_alter_instructorassignment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Хичээл ороогүй эсэх'),
        ),
    ]
