# Generated by Django 5.2.7 on 2025-11-16 09:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0007_classsession_is_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Гүйлгээний огноо')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Дүн')),
                ('description', models.TextField(verbose_name='Гүйлгээний утга')),
                ('reference_number', models.CharField(blank=True, max_length=200, verbose_name='Лавлагааны дугаар')),
                ('payer_name', models.CharField(blank=True, max_length=200, verbose_name='Төлөгчийн нэр')),
                ('status', models.CharField(choices=[('PENDING', 'Хүлээгдэж буй'), ('MATCHED', 'Холбогдсон'), ('PARTIALLY_MATCHED', 'Хэсэгчлэн холбогдсон'), ('IGNORED', 'Орхигдсон')], default='PENDING', max_length=20, verbose_name='Төлөв')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Импортлосон огноо')),
            ],
            options={
                'verbose_name': 'Банкны гүйлгээ',
                'verbose_name_plural': 'Банкны гүйлгээнүүд',
                'ordering': ['-transaction_date', '-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_payments', to='aikido_app.banktransaction', verbose_name='Банкны гүйлгээ'),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_month', models.DateField(verbose_name='Төлбөрийн сар')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Дүн')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='aikido_app.banktransaction', verbose_name='Банкны гүйлгээ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aikido_app.instructor', verbose_name='Үүсгэсэн хэрэглэгч')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='aikido_app.student', verbose_name='Сурагч')),
            ],
            options={
                'verbose_name': 'Төлбөрийн хуваарилалт',
                'verbose_name_plural': 'Төлбөрийн хуваарилалтууд',
                'ordering': ['-created_at'],
            },
        ),
    ]
