# Generated by Django 5.2.7 on 2025-11-16 09:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0008_banktransaction_payment_bank_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Эцсийн үлдэгдэл'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='counterparty_account',
            field=models.CharField(blank=True, max_length=500, verbose_name='Харьцсан данс'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Кредит гүйлгээ'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='debit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Дебит гүйлгээ'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Эхний үлдэгдэл'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Кредит гүйлгээний дүн', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Дүн (кредит)'),
        ),
    ]
