# Generated by Django 5.2.8 on 2025-11-16 10:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0009_banktransaction_closing_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Нэр')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
            ],
            options={
                'verbose_name': 'Зардлын ангилал',
                'verbose_name_plural': 'Зардлын ангиллууд',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Дүн')),
                ('expense_date', models.DateField(help_text='Зардал гарсан огноо', verbose_name='Зардлын огноо')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_allocations', to='aikido_app.banktransaction', verbose_name='Банкны гүйлгээ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aikido_app.instructor', verbose_name='Үүсгэсэн хэрэглэгч')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='aikido_app.expensecategory', verbose_name='Зардлын ангилал')),
            ],
            options={
                'verbose_name': 'Зардлын хуваарилалт',
                'verbose_name_plural': 'Зардлын хуваарилалтууд',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
