# Generated by Django 5.2.8 on 2025-11-16 12:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0010_expensecategory_expenseallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Нэр')),
                ('category_type', models.CharField(choices=[('SEMINAR', 'Семинарын хураамж'), ('MEMBERSHIP', 'Гишүүнчлэлийн хураамж'), ('EXAM', 'Шалгалтын хураамж'), ('EVENT', 'Арга хэмжээний орлого'), ('MERCHANDISE', 'Бараа борлуулалт'), ('OTHER', 'Бусад орлого')], default='OTHER', max_length=20, verbose_name='Төрөл')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
            ],
            options={
                'verbose_name': 'Орлогын ангилал',
                'verbose_name_plural': 'Орлогын ангиллууд',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncomeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField(verbose_name='Орлогын огноо')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Дүн')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_allocations', to='aikido_app.banktransaction', verbose_name='Банкны гүйлгээ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aikido_app.instructor', verbose_name='Үүсгэсэн хэрэглэгч')),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aikido_app.incomecategory', verbose_name='Орлогын ангилал')),
            ],
            options={
                'verbose_name': 'Орлогын хуваарилалт',
                'verbose_name_plural': 'Орлогын хуваарилалтууд',
                'ordering': ['-created_at'],
            },
        ),
    ]
