# Generated by Django 5.2.8 on 2025-11-16 13:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0011_incomecategory_incomeallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('seminar_date', models.DateField(verbose_name='Семинарын огноо')),
                ('fee', models.DecimalField(decimal_places=2, help_text='Нэг хүний төлбөр', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Төлбөр')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
            ],
            options={
                'verbose_name': 'Семинар',
                'verbose_name_plural': 'Семинарууд',
                'ordering': ['-seminar_date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_month', models.DateField(help_text='Аль сарын гишүүнчлэлийн төлбөр', verbose_name='Төлбөрийн сар')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Төлсөн дүн')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_allocations', to='aikido_app.banktransaction', verbose_name='Банкны гүйлгээ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aikido_app.instructor', verbose_name='Үүсгэсэн хэрэглэгч')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aikido_app.student', verbose_name='Сурагч')),
            ],
            options={
                'verbose_name': 'Гишүүнчлэлийн төлбөр',
                'verbose_name_plural': 'Гишүүнчлэлийн төлбөрүүд',
                'ordering': ['-payment_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeminarPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Төлсөн дүн')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_allocations', to='aikido_app.banktransaction', verbose_name='Банкны гүйлгээ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aikido_app.instructor', verbose_name='Үүсгэсэн хэрэглэгч')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aikido_app.seminar', verbose_name='Семинар')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aikido_app.student', verbose_name='Сурагч')),
            ],
            options={
                'verbose_name': 'Семинарын төлбөр',
                'verbose_name_plural': 'Семинарын төлбөрүүд',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'seminar')},
            },
        ),
    ]
