# Generated by Django 5.2.7 on 2025-11-17 05:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0012_seminar_membershippaymentallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFederationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Тухайн сарын эхний өдөр', verbose_name='Сар')),
                ('total_payment_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Энэ ангийн сурагчдаас цуглуулсан сарын төлбөрийн нийт дүн', max_digits=12, verbose_name='Цуглуулсан нийт төлбөр')),
                ('federation_share_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Холбоонд олгох төлбөр (50%)', max_digits=12, verbose_name='Холбооны хувь')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Олгосон эсэх')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Олгосон огноо')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aikido_app.classtype', verbose_name='Ангийн төрөл')),
            ],
            options={
                'verbose_name': 'Холбооны сарын төлбөр',
                'verbose_name_plural': 'Холбооны сарын төлбөрүүд',
                'ordering': ['-month', 'class_type'],
                'unique_together': {('class_type', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyInstructorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Тухайн сарын эхний өдөр', verbose_name='Сар')),
                ('role', models.CharField(choices=[('LEAD', 'Ахлах багш'), ('ASSISTANT', 'Туслах багш')], max_length=20, verbose_name='Үүрэг')),
                ('total_classes', models.IntegerField(default=0, help_text='Тухайн сард заасан хичээлийн тоо', verbose_name='Нийт хичээлийн тоо')),
                ('total_payment_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Энэ ангийн сурагчдаас цуглуулсан сарын төлбөрийн нийт дүн', max_digits=12, verbose_name='Цуглуулсан нийт төлбөр')),
                ('instructor_share_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Багшид олгох төлбөр (50%-ийн 60% эсвэл 40%)', max_digits=12, verbose_name='Багшийн хувь')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Олгосон эсэх')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Олгосон огноо')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aikido_app.classtype', verbose_name='Ангийн төрөл')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='aikido_app.instructor', verbose_name='Багш')),
            ],
            options={
                'verbose_name': 'Багшийн сарын төлбөр',
                'verbose_name_plural': 'Багшийн сарын төлбөрүүд',
                'ordering': ['-month', 'class_type', 'instructor'],
                'unique_together': {('instructor', 'class_type', 'month', 'role')},
            },
        ),
    ]
