# Generated by Django 5.2.7 on 2025-11-17 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0013_monthlyfederationpayment_monthlyinstructorpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfederationpayment',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, help_text='Төлбөр олгосон банкны гүйлгээ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federation_payments', to='aikido_app.banktransaction', verbose_name='Банкны гүйлгээ'),
        ),
        migrations.AddField(
            model_name='monthlyinstructorpayment',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, help_text='Төлбөр олгосон банкны гүйлгээ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_payments', to='aikido_app.banktransaction', verbose_name='Банкны гүйлгээ'),
        ),
    ]
