# Generated by Django 5.2.7 on 2025-11-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0015_alter_instructor_user_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='allowed_class_types',
            field=models.ManyToManyField(blank=True, help_text='Энэ багш эдгээр ангиудын төлбөрийг харна (хоосон бол бүх ангийг харна)', related_name='allowed_instructors', to='aikido_app.classtype', verbose_name='Харах эрхтэй ангиуд'),
        ),
    ]
