# Generated by Django 5.2.7 on 2025-11-21 06:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0016_instructor_allowed_class_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinstructorpayment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Одоогоор төлсөн нийт дүн', max_digits=12, verbose_name='Төлсөн дүн'),
        ),
        migrations.CreateModel(
            name='InstructorPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Дүн')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_payment_allocations', to='aikido_app.banktransaction', verbose_name='Банкны гүйлгээ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aikido_app.instructor', verbose_name='Үүсгэсэн хэрэглэгч')),
                ('instructor_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='aikido_app.monthlyinstructorpayment', verbose_name='Багшийн төлбөр')),
            ],
            options={
                'verbose_name': 'Багшийн төлбөрийн хуваарилалт',
                'verbose_name_plural': 'Багшийн төлбөрийн хуваарилалтууд',
                'ordering': ['-created_at'],
            },
        ),
    ]
