# Generated by Django 5.2.8 on 2025-11-21 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0017_monthlyinstructorpayment_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentallocation',
            name='attendance_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ирсэн ирцийн тоо'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Тайлбар/Коммент'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='highlight_color',
            field=models.CharField(blank=True, choices=[('', 'Өнгөгүй'), ('green', 'Ногоон'), ('blue', 'Цэнхэр'), ('yellow', 'Шар'), ('red', 'Улаан'), ('purple', 'Ягаан'), ('pink', 'Ягаан (цайвар)'), ('orange', 'Улбар шар'), ('gray', 'Саарал')], default='', max_length=20, verbose_name='Онцлох өнгө'),
        ),
    ]
