# Generated by Django 5.2.8 on 2025-11-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0018_paymentallocation_attendance_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCellComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Тухайн сарын эхний өдөр', verbose_name='Сар')),
                ('comment', models.TextField(blank=True, verbose_name='Коммент')),
                ('highlight_color', models.CharField(blank=True, choices=[('', 'Өнгөгүй'), ('green', 'Ногоон'), ('blue', 'Цэнхэр'), ('yellow', 'Шар'), ('red', 'Улаан'), ('purple', 'Нил ягаан'), ('pink', 'Ягаан'), ('orange', 'Улбар шар'), ('gray', 'Саарал')], default='', max_length=10, verbose_name='Өнгө')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_comments', to='aikido_app.student', verbose_name='Сурагч')),
            ],
            options={
                'verbose_name': 'Нүдний коммент',
                'verbose_name_plural': 'Нүдний комментүүд',
                'ordering': ['student', '-month'],
                'unique_together': {('student', 'month')},
            },
        ),
    ]
