# Generated by Django 5.2.7 on 2025-11-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0019_paymentcellcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='can_view_all_payments',
            field=models.BooleanField(default=False, help_text='Идэвхжүүлбэл энэ багш бусад багш нарын цалинг харна', verbose_name='Бүх багшийн цалин харах эрх'),
        ),
    ]
