# Generated by Django 5.2.7 on 2025-11-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0020_instructor_can_view_all_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Даваа'), (1, 'Мягмар'), (2, 'Лхагва'), (3, 'Пүрэв'), (4, 'Баасан'), (5, 'Бямба'), (6, 'Ням')], verbose_name='Гараг'),
        ),
    ]
