# Generated by Django 5.2.7 on 2025-11-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aikido_app', '0021_alter_classsession_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_fee_exempt',
            field=models.BooleanField(default=False, help_text='Хэрвээ тэмдэглэсэн бол сарын төлбөр төлөх шаардлагагүй', verbose_name='Төлбөрөөс чөлөөлөгдсөн эсэх'),
        ),
    ]
